Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2018-04, with the labels that each got.

#653 Update plugin-fitnesse.yml
  permissions/plugin-fitnesse.yml
Labels: authorization OK

#641 Add config for gerrit plugin
  permissions/plugin-gerrit-code-review.yml
Labels: needs fix

#652 [Follow-up to HOSTING-530] Enable deployment
  permissions/plugin-build-token-trigger.yml
Labels: needs fix

#666 Added agentgonzo to kubernetes-credentials-provider
  permissions/plugin-kubernetes-credentials-provider.yml
Labels: needs authorization

#663 Add config for platformlabeler plugin
  permissions/plugin-platformlabeler.yml
Labels: authorization OK

#674 Add michallaskowski as dev to plugin-usage-plugin
  permissions/plugin-plugin-usage-plugin.yml
Labels: initial login OK
