Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2018-02, with the labels that each got.

#605 Grant @oleg-nenashev permissions to release the JDepend plugin
  permissions/plugin-jdepend.yml
Labels: authorization OK

#584 changing maintainer and devs for the iTest plugin
  permissions/plugin-itest.yml
Labels: needs hosting

#607 Add LoadBalance Plugin
  permissions/plugin-agent-loadbalance.yml
Labels: needs fix

#559 [HOSTING-492][HOSTING-512] add Kotlin 1.x Standard Library
  permissions/plugin-kotlin-v1-stdlib-jdk8.yml
  permissions/pom-kotlin-plugin.yml
Labels: needs hosting
