Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2018-08, with the labels that each got.

#798 Add lvotypkova as maintainer.
  permissions/plugin-nested-view.yml
Labels: authorized unless rejected

#799 Add myself as uploader for the dashboard-view plugin
  permissions/plugin-dashboard-view.yml
Labels: needs authorization

#821 Create plugin-synopsys-coverity.yml
  permissions/plugin-synopsys-coverity.yml
Labels: needs clarification
