Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2018-06, with the labels that each got.

#721 Permission Request for plugin-influxdb-query
  permissions/plugin-influxdb-query.yml
Labels: needs fix

#727 Update plugin-cerberus-testing.yml
  permissions/plugin-cerberus-testing.yml
Labels: needs authorization

#678 Add @dwnusbaum to credentials maintainers
  permissions/plugin-credentials.yml
Labels: needs authorization

#732 Update plugin-teamconcert-git.yml
  permissions/plugin-teamconcert-git.yml
Labels: needs authorization

#738 Grant @oleg-nenashev permissions to release the Locale Plugin
  permissions/plugin-locale.yml
Labels: authorization OK

#741 Add @stephen-badger as a maintainer of metrics
  permissions/plugin-metrics.yml
Labels: authorization OK
