Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2018-12, with the labels that each got.

#952 apply permission for list-git-branches-parameter plugin
  permissions/plugin-list-git-branches-parameter.yml
Labels: needs clarification

#953 Add ws-execution-manager plugin
  permissions/plugin-ws-execution-manager.yml
Labels: needs response

#967 permission request for yorammi
  permissions/plugin-jenkins-multijob-plugin.yml
Labels: authorization OK

#966 Request permission for azure-container-registry-plugin
  permissions/plugin-azure-container-registry-tasks.yml
Labels: authorization OK

#955 Add pierrebtz as audit-trail-plugin maintainer
  permissions/plugin-audit-trail.yml
Labels: authorized unless rejected

#960 Request upload permission for Katalon plugin
  permissions/plugin-katalon.yml
Labels: needs initial login

#971 Adding Gavin and David to maintainers list
  permissions/plugin-sse-gateway.yml
Labels: authorization OK

#969 Add dmotpan as a developer
  permissions/plugin-github-pr-coverage-status.yml
Labels: authorization OK
