Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2018-05, with the labels that each got.

#688 Grant @patcadelina and @oleg-nenashev permissions to release AWS Device Farm Plugin.
  permissions/plugin-aws-device-farm.yml
Labels: authorization OK

#685 Permissions added for alauda-devops-sync
  permissions/plugin-alauda-devops-sync.yml
Labels: needs initial login

#691 add cashlalala as developer
  permissions/plugin-Parameterized-Remote-Trigger.yml
Labels: initial login OK
