Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2018-11, with the labels that each got.

#895 Added myself as a developer for Fitnesse plugin
  permissions/plugin-fitnesse.yml
Labels: authorization OK

#923 Create plugin Tuleap Git Branch Source
  permissions/plugin-tuleap-git-branch-source.yml
Labels: hosting OK, initial login OK

#917 Create plugin-linchpin.yml
  permissions/plugin-linchpin.yml
Labels: needs fix

#930 Permissions for the plugin as well as for the component
  permissions/plugin-async-http-client.yml
Labels: needs authorization

#898 Update permissions list for Code Dx plugin
  permissions/plugin-codedx.yml
Labels: authorized unless rejected

#939 Requesting write access to mailer plugin
  permissions/plugin-mailer.yml
Labels: authorization OK

#942 Add timja to slack-plugin
  permissions/plugin-slack.yml
Labels: authorization OK

#944 Add "imeredith" to blueocean-executor-info-plugin upload
  permissions/plugin-blueocean-executor-info.yml
Labels: authorization OK
