Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2019-01, with the labels that each got.

#981 Add plugin-ci-with-toad-devops-toolkit upload permission to kevinmdalton
  permissions/plugin-ci-with-toad-devops-toolkit.yml
Labels: authorization OK

#989 Add @batmat to releasers of extras-executable-war
  permissions/component-executable-war.yml
Labels: authorization OK

#988 Give upload permission
  permissions/plugin-ca-apm.yml
Labels: authorization OK

#980 [JENKINS-55434] Permissions for audit-log-plugin
  permissions/plugin-audit-log.yml
Labels: hosting OK

#963 added user bschulte3 to plugin-kryptowire
  permissions/plugin-kryptowire.yml
Labels: authorization OK

#991 Add jvz as ec2 maintainer
  permissions/plugin-ec2.yml
Labels: authorization OK

#1000 Add permissions for insightappsec-plugin
  permissions/plugin-insightappsec.yml
Labels: hosting OK

#1009 Update maintainer (temporary only)
  permissions/plugin-openid.yml
Labels: authorization OK

#992 Update plugin-vectorcast-coverage.yml
  permissions/plugin-vectorcast-coverage.yml
Labels: authorization OK

#993 Update plugin-vectorcast-execution.yml
  permissions/plugin-vectorcast-execution.yml
Labels: authorization OK

#1003 Add benchmark-evaluator permission file
  permissions/plugin-benchmark-evaluator.yml
Labels: hosting OK, initial login OK, request syntax OK

#1004 Add YAML for testproject-plugin
  permissions/plugin-testproject.yml
Labels: needs fix

#1007 Updates maintainer for the sidebar-link plugin
  permissions/plugin-sidebar-link.yml
Labels: authorization OK

#1008 Add eiffel-broadcaster permission file
  permissions/plugin-eiffel-broadcaster.yml
Labels: needs fix

#1013 Allow Oleg and Baptiste to release lib-version-number
  permissions/component-version-number.yml
Labels: authorization OK, initial login OK

#1014 Adopting stash-pullrequest-builder-plugin
  permissions/plugin-stash-pullrequest-builder.yml
Labels: authorization OK

#941 Add @butchyyyy to the list of Zulip plugin maintainers
  permissions/plugin-humbug.yml
Labels: needs authorization, needs response
