Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2019-10, with the labels that each got.

#1291 Add aheritier as maintainer of cloudbees-jenkins-advisor
  permissions/plugin-cloudbees-jenkins-advisor.yml
Labels: authorization OK

#1293 Add Bobby and Fran to git and git client plugins
  permissions/plugin-git-client.yml
  permissions/plugin-git.yml
Labels: authorization OK

#1294 Add myself as the developer of oic-auth plugin
  permissions/plugin-oic-auth.yml
Labels: authorization OK

#1302 aws beanstalk releaser plugin
  permissions/plugin-aws-beanstalk-releaser.yml
Labels: needs fix

#1305 added froque as maintainer to powershell plugin
  permissions/plugin-powershell.yml
Labels: needs authorization
