Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2019-12, with the labels that each got.

#1277 Remove lvotypko from release permissions
  permissions/plugin-Matrix-sorter-plugin.yml
  permissions/plugin-disk-usage.yml
  permissions/plugin-upstream-downstream-view.yml
Labels: needs authorization, needs fix

#1361 Add 2 new developers to tuleap-git-branch-source
  permissions/plugin-tuleap-git-branch-source.yml
Labels: authorization OK

#1362 Add nre_ableton to JenkinsPipelineUnit
  permissions/component-jenkins-pipeline-unit.yml
Labels: authorization OK

#1342 Add mihai_virag as developer
  permissions/plugin-silk-performer-plugin.yml
Labels: needs fix

#1367 Adding alexandernikitin again
  permissions/plugin-soapui-pro-functional-testing.yml
Labels: authorization OK

#1368 Add mramonleon to async-http-plugin
  permissions/plugin-async-http-client.yml
Labels: authorization OK
