Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2019-03, with the labels that each got.

#1049 Grant @oleg-nenashev and @olivergondza permissions to release the Javadoc plugin
  permissions/plugin-javadoc.yml
Labels: authorization OK

#1051 Request permission for egutierrez and fcojfernandez
  permissions/component-custom-war-packager-cli.yml
  permissions/component-custom-war-packager-lib.yml
  permissions/component-custom-war-packager-maven-plugin.yml
  permissions/pom-custom-war-packager-parent-pom.yml
Labels: authorization OK

#1055 Grant @oleg-nenashev permissions to release the Unique ID plugin
  permissions/plugin-unique-id.yml
Labels: authorization OK

#1056 Grant @oleg-nenashev permissions to release the plugin
  permissions/plugin-ssh-credentials.yml
Labels: authorization OK

#1059 grant @daverted permissions to overops-query-plugin
  permissions/plugin-overops-query.yml
Labels: needs authorization

#1031 Adding myself to plugin-jx-resources.yml
  permissions/plugin-jx-resources.yml
Labels: needs authorization

#1054 Request permissions for @car-roll
  permissions/plugin-durable-task.yml
  permissions/plugin-github-branch-source.yml
  permissions/plugin-pipeline-graph-analysis.yml
  permissions/plugin-pipeline-input-step.yml
  permissions/plugin-pipeline-milestone-step.yml
  permissions/plugin-pipeline-stage-step.yml
  permissions/plugin-pipeline-stage-view.yml
  permissions/plugin-script-security.yml
  permissions/plugin-structs.yml
  permissions/plugin-workflow-aggregator.yml
  permissions/plugin-workflow-api.yml
  permissions/plugin-workflow-basic-steps.yml
  permissions/plugin-workflow-cps-global-lib.yml
  permissions/plugin-workflow-cps.yml
  permissions/plugin-workflow-durable-task-step.yml
  permissions/plugin-workflow-job.yml
  permissions/plugin-workflow-multibranch.yml
  permissions/plugin-workflow-scm-step.yml
  permissions/plugin-workflow-support.yml
Labels: authorization OK

#1068 Add maintainers to favorite and display-url-api
  permissions/plugin-display-url-api.yml
  permissions/plugin-favorite.yml
Labels: authorization OK

#1072 Grant permissions to Zoom
  permissions/plugin-zoom.yml
Labels: needs fix
