Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2019-04, with the labels that each got.

#1088 Update plugin-basic-branch-build-strategies.yml
  permissions/plugin-basic-branch-build-strategies.yml
Labels: authorization OK

#1093 request permission for plugin-nomad
  permissions/plugin-nomad.yml
Labels: needs authorization

#1104 scmskip-plugin publish permission
  permissions/plugin-scmskip.yml
Labels: needs initial login

#1091 Change plugin maintainer and adding security contact
  permissions/plugin-aqua-microscanner.yml
  permissions/plugin-aqua-security-scanner.yml
  permissions/plugin-aqua-serverless.yml
Labels: needs authorization
