Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2020-07, with the labels that each got.

#1601 Request permission for plugin-libvirt-slave
  permissions/plugin-libvirt-slave.yml
Labels: authorization OK

#1602 Plugin GitHub checks
  permissions/plugin-github-checks.yml
Labels: needs fix

#1613 Create plugin-zerobug.yml
  permissions/plugin-zerobug.yml
Labels: needs hosting, on-hold

#1619 Added myself as developer to bitbucket-plugin
  permissions/plugin-bitbucket.yml
Labels: authorization OK

#1625 Add new synomtv user to plugin-defensics developers.
  permissions/plugin-defensics.yml
Labels: needs authorization
