Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2020-11, with the labels that each got.

#1742 Grant @oleg-nenashev permissions to release Conditional Build Step
  permissions/plugin-conditional-buildstep.yml
Labels: needs authorization

#1743 Grant @oleg-nenashev permissions to release the HTTP Request plugin
  permissions/plugin-http_request.yml
Labels: authorization OK

#1745 Add jglick to reverse-proxy-auth-plugin
  permissions/plugin-reverse-proxy-auth-plugin.yml
Labels: authorization OK

#1751 adding jtaboada to bitbucket branch source
  permissions/plugin-cloudbees-bitbucket-branch-source.yml
Labels: needs authorization, needs fix

#1749 Adopt build blocker plugin.
  permissions/plugin-build-blocker-plugin.yml
Labels: authorized unless rejected

#1756 Add new maintainers to fortify-plugin
  permissions/plugin-fortify.yml
Labels: needs authorization
