Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2020-03, with the labels that each got.

#1439 zohosprints-plugin permission file
  permissions/plugin-zohosprints.yml
Labels: needs fix

#1427 Adopt thin backup plugin
  permissions/plugin-thinBackup.yml
Labels: on-hold

#1410 Grant nivkeidan release permission for anka-build plugin
  permissions/plugin-anka-build.yml
Labels: needs authorization

#1458 timja ssh-cli-auth-module release permissions
  permissions/component-ssh-cli-auth.yml
Labels: needs authorization

#1426 permissions for new maintainer to upload cucumber-slack-notifier plugin
  permissions/plugin-cucumber-slack-notifier.yml
Labels: needs authorization

#1457 Adding jtaboada to maven-plugin
  permissions/plugin-maven-plugin.yml
Labels: needs authorization

#1473 Adding to the maintainers list for this plugin
  permissions/plugin-anchore-container-scanner.yml
Labels: authorization OK

#1475 Add TobiX as maintainer of the compact-columns plugin
  permissions/plugin-compact-columns.yml
Labels: authorization OK

#1477 Add ericcitaire as developper of docker-java-api after plugin adoption
  permissions/plugin-docker-java-api.yml
Labels: authorization OK

#1482 Add @robinsoc as developer of tuleap-api-plugin
  permissions/plugin-tuleap-api.yml
Labels: authorization OK

#1479 Add developer to VectorCAST plugins
  permissions/plugin-vectorcast-coverage.yml
  permissions/plugin-vectorcast-execution.yml
Labels: authorization OK
