Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2020-05, with the labels that each got.

#1523 add daniel_akua to experitest-cloud-plugin developers
  permissions/plugin-experitest-cloud.yml
Labels: needs authorization

#1533 Add mramonleon to ec2-plugin
  permissions/plugin-ec2.yml
Labels: authorization OK

#1549 Requesting for release permissions on Aqua plugins
  permissions/plugin-aqua-security-scanner.yml
Labels: needs fix

#1553 tomasbjerre only developer of git-changelog-plugin
  permissions/plugin-git-changelog.yml
Labels: needs authorization
