Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2020-06, with the labels that each got.

#1560 Add johanc as a developer on deepsecurity-smartcheck-plugin
  permissions/plugin-deepsecurity-smartcheck.yml
Labels: needs authorization

#1561 create new split-admin plugin
  permissions/plugin-split-admin.yml
Labels: needs fix

#1565 [INFRA-2619] Grant releasebot permission on remoting library
  permissions/component-remoting-test-client.yml
  permissions/component-remoting.yml
Labels: needs authorization

#1573 Permission for rarabaolaza on mock-security-realm
  permissions/plugin-mock-security-realm.yml
Labels: authorization OK

#1575 Restore access to afalko after relogin
  permissions/plugin-redis-fingerprint-storage.yml
Labels: authorization OK

#1596 Request upload permissions for build-user-vars-plugin.
  permissions/plugin-build-user-vars-plugin.yml
Labels: authorization OK
