Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2020-08, with the labels that each got.

#1632 Add release permissions for Commons HttpClient Lib fork
  permissions/component-commons-httpclient.yml
Labels: authorization OK

#1626 Added uleska-plugin
  permissions/plugin-uleska.yml
Labels: on-hold

#1627 Add timja and uhafner to code-coverage-api
  permissions/plugin-code-coverage-api.yml
Labels: authorized unless rejected

#1638 Add aheritier as maintainer of pipeline-maven plugin
  permissions/plugin-pipeline-maven.yml
Labels: authorization OK

#1646 Add timja to database, database-h2 and database-postgresql
  permissions/plugin-database-h2.yml
  permissions/plugin-database-postgresql.yml
  permissions/plugin-database.yml
Labels: authorization OK
