Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2021-11, with the labels that each got.

#2148 Update permissions, add addtional developer
  permissions/plugin-ws-execution-manager.yml
Labels: needs authorization

#2157 Add CloudBees colleagues to some plugins I maintain
  permissions/plugin-aws-credentials.yml
  permissions/plugin-kubernetes.yml
Labels: initial login OK, authorization OK

#2167 Adoption request for "webhook-step" plugin
  permissions/plugin-webhook-step.yml
Labels: needs authorization

#2150 Adopt plugin-hidden-parameter plugin
  permissions/plugin-hidden-parameter.yml
Labels: authorized unless rejected

#2155 Updated developer permissions [xldeploy-plugin && xlrelease-plugin]
  permissions/plugin-deployit-plugin.yml
  permissions/plugin-xlrelease-plugin.yml
Labels: needs authorization

#2171 Update plugin-teamconcert.yml
  permissions/plugin-teamconcert.yml
Labels: needs initial login, authorization OK

#2172 Update plugin-teamconcert-git.yml
  permissions/plugin-teamconcert-git.yml
Labels: needs initial login, authorization OK, on-hold

#2149 add cloudbees dev. team to OSS plugins that CB (co-)maintains
  permissions/plugin-artifact-manager-s3.yml
  permissions/plugin-aws-credentials.yml
  permissions/plugin-aws-global-configuration.yml
  permissions/plugin-aws-java-sdk.yml
  permissions/plugin-azure-publishersettings-credentials.yml
  permissions/plugin-kubernetes-client-api.yml
  permissions/plugin-kubernetes-credentials.yml
  permissions/plugin-kubernetes.yml
  permissions/plugin-mapdb-api.yml
  permissions/plugin-view-job-filters.yml
Labels: authorized unless rejected

#2200 Update plugin-abap-ci.yml
  permissions/plugin-abap-ci.yml
Labels: needs initial login
