Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2022-10, with the labels that each got.

#2822 Add nfalco as mantainer of dependency-check-plugin
  permissions/plugin-dependency-check-jenkins-plugin.yml
Labels: authorized unless rejected

#2797 Add `basil` to `adoptopenjdk`
  permissions/plugin-adoptopenjdk.yml
Labels: authorized unless rejected

#2837 Add 2 users as admin of openshift-client-plugin
  permissions/plugin-openshift-client.yml
Labels: needs initial login

#2838 Update plugin-pipeline-stage-view.yml
  permissions/plugin-pipeline-stage-view.yml
Labels: needs initial login

#2879 Add jack_zhang in basic-branch-build-strategies
  permissions/plugin-basic-branch-build-strategies.yml
Labels: authorization OK

#2884 Add mpokornyetm to develop lists in the lockable-resource plugin
  permissions/plugin-lockable-resources.yml
Labels: needs authorization

#2888 Add atrigueiro to Jira devs list
  permissions/plugin-atlassian-jira-software-cloud.yml
Labels: needs authorization, initial login OK

#2895 Synopsys coverity plugin adoption
  permissions/plugin-synopsys-coverity.yml
Labels: needs authorization

#2841 申请插件维护权限
  permissions/plugin-upload-pgyer.yml
Labels: authorized unless rejected

#2901 Adding Prabodh as the new maintainer.
  permissions/plugin-teamconcert.yml
Labels: needs authorization, initial login OK
