Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2022-02, with the labels that each got.

#2350 Adopt (orphaned) deployed-on-column
  permissions/plugin-deployed-on-column.yml
Labels: authorization OK

#2349 Adopt mstestrunner
  permissions/plugin-mstestrunner.yml
Labels: authorization OK

#2351 Add myself to authorized BigPanda developers
  permissions/plugin-bigpanda-jenkins.yml
Labels: needs initial login, authorization OK

#2365 Enable CD for my plugin
  permissions/plugin-buildtriggerbadge.yml
Labels: initial login OK, authorization OK

#2367 plugin-publish-over-ssh +olamy
  permissions/plugin-publish-over-ssh.yml
Labels: needs authorization

#2363 Propose help from CloudBees on security issues
  permissions/plugin-javax-activation-api.yml
  permissions/plugin-javax-mail-api.yml
Labels: authorization OK

#2378 Get maintainer access on some Google plugins
  permissions/plugin-google-compute-engine.yml
  permissions/plugin-google-kubernetes-engine.yml
  permissions/plugin-google-metadata-plugin.yml
  permissions/plugin-google-oauth-plugin.yml
  permissions/plugin-google-storage-plugin.yml
Labels: authorization OK

#2389 [ldap] Add CloudBees team to help
  permissions/plugin-ldap.yml
Labels: authorization OK

#2395 Adding new developer for soapui-pro-functional-testing-plugin
  permissions/plugin-soapui-pro-functional-testing.yml
Labels: needs authorization

#2419 chore: Enable CD for envinject lib
  permissions/component-envinject-lib.yml
Labels: needs authorization, authorization OK
