Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2022-11, with the labels that each got.

#2916 Add teilo to workflow plugins
  permissions/plugin-workflow-durable-task-step.yml
  permissions/plugin-workflow-multibranch.yml
  permissions/plugin-workflow-scm-step.yml
  permissions/plugin-workflow-step-api.yml
  permissions/plugin-workflow-support.yml
Labels: authorization OK

#2933 Add Mark Waite as a cloud stats plugin developer
  permissions/plugin-cloud-stats.yml
Labels: needs authorization

#2945 Adopt junit-attachments
  permissions/plugin-junit-attachments.yml
Labels: authorization OK

#2968 Add markewaite as an xshell plugin maintainer
  permissions/plugin-xshell.yml
Labels: authorization OK

#2962 Add cjerad to ec2-fleet-plugin
  permissions/plugin-ec2-fleet.yml
Labels: authorization OK

#2961 Archive evergreen-plugin
  permissions/plugin-evergreen.yml
Labels: on-hold

#2919 Add `basil` to `jdepend`
  permissions/plugin-jdepend.yml
Labels: authorized unless rejected

#2958 Add `basil` to `github-pr-coverage-status`
  permissions/plugin-github-pr-coverage-status.yml
Labels: authorized unless rejected

#2944 Add `basil` to `nexus-artifact-uploader`
  permissions/plugin-nexus-artifact-uploader.yml
Labels: authorized unless rejected

#2937 add chas as developer to plugin-extended-choice-parameter
  permissions/plugin-extended-choice-parameter.yml
Labels: authorized unless rejected

#2956 Add `basil` to `ivy`
  permissions/plugin-ivy.yml
Labels: authorized unless rejected

#2987 added user prakhar_jenkins which refers to prakhar saxena
  permissions/plugin-aqua-security-scanner.yml
Labels: authorization OK

#2991 Add Cyberark devs Nitin & Jaleela as r/w users
  permissions/plugin-conjur-credentials.yml
Labels: authorization OK

#3006 Add teilo as a developer of plugin-compat-tester
  permissions/component-plugins-compat-tester.yml
Labels: authorization OK
