Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2023-03, with the labels that each got.

#3114 Adopt TestComplete-plugin
  permissions/plugin-TestComplete.yml
Labels: authorized unless rejected

#3170 Add dfchang336 to CodePipeline plugin maintainers
  permissions/plugin-aws-codepipeline.yml
Labels: authorization OK

#3178 Request for comaintainership of shutdown-queue-plugin
  permissions/plugin-shutdown-queue.yml
Labels: needs authorization

#3190 Adopt postgresql-api-plugin
  permissions/plugin-postgresql-api.yml
Labels: authorization OK

#3189 Adopt h2-api-plugin
  permissions/plugin-h2-api.yml
Labels: authorization OK

#3093 CD gatling plugin
  permissions/plugin-gatling.yml
Labels: needs authorization

#3196 add olamy in few google plugins
  permissions/plugin-google-compute-engine.yml
  permissions/plugin-google-kubernetes-engine.yml
  permissions/plugin-google-metadata-plugin.yml
  permissions/plugin-google-oauth-plugin.yml
  permissions/plugin-google-storage-plugin.yml
Labels: authorization OK

#3209 Update plugin-google-chat-notification.yml
  permissions/plugin-google-chat-notification.yml
Labels: needs authorization

#3216 Add pdk27 to ec2-fleet-plugin
  permissions/plugin-ec2-fleet.yml
Labels: needs authorization
