Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2023-01, with the labels that each got.

#3055 Let markewaite adopt cron column plugin
  permissions/plugin-cron_column.yml
Labels: authorization OK

#3057 Enable CD for `subversion`
  permissions/plugin-subversion.yml
Labels: authorization OK

#3058 Add Bevigil user to bevigil-ci-plugin
  permissions/plugin-bevigil-ci.yml
Labels: needs initial login

#3053 Let markewaite adopt slave-setup plugin
  permissions/plugin-slave-setup.yml
Labels: needs authorization

#3067 Request maintainer role
  permissions/plugin-prometheus.yml
Labels: needs authorization

#3072 Add new members for plugin-autify
  permissions/plugin-autify.yml
Labels: authorization OK

#3074 Add myself to the plugin-ascii-magician
  permissions/plugin-ascii-magician.yml
Labels: needs authorization

#3100 Update Code Dx plugin permissions
  permissions/plugin-codedx.yml
Labels: needs initial login

#3103 Add markewaite as mask-passwords maintainer
  permissions/plugin-mask-passwords.yml
Labels: needs authorization

#3095 Adding user(srinivas0731) to Aqua plugin developer list
  permissions/plugin-aqua-security-scanner.yml
Labels: authorization OK

#3105 Adopt Ansible plugin
  permissions/plugin-ansible.yml
Labels: needs authorization
