Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2023-07, with the labels that each got.

#3382 Add `basil` to `git-parameter`
  permissions/plugin-git-parameter.yml
Labels: authorized unless rejected

#3427 Updating the teams/openshift-developers.yml
  teams/openshift-developers.yml
Labels: needs authorization

#3425 github-oauth: Add scurvydoggo
  permissions/plugin-github-oauth.yml
Labels: needs authorization, needs initial login

#3409 Add basil to categorized-view
  permissions/plugin-categorized-view.yml
Labels: authorized unless rejected

#3438 Add basil to plugin-extensible-choice-parameter
  permissions/plugin-extensible-choice-parameter.yml
Labels: authorization OK

#3454 Add `basil` to `chucknorris`
  permissions/plugin-chucknorris.yml
Labels: needs authorization

#3457 Update plugin-remote-jobs-view-plugin.yml
  permissions/plugin-remote-jobs-view-plugin.yml
Labels: needs initial login
