Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2023-02, with the labels that each got.

#3122 Adopt performance plugin
  permissions/plugin-performance.yml
Labels: authorization OK

#3115 Update developers on permissions to bigpanda plugin
  permissions/plugin-bigpanda-jenkins.yml
Labels: needs initial login, authorization OK

#3131 Add diegolovison to plugin-radargun
  permissions/plugin-radargun.yml
Labels: needs authorization
