Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2024-07, with the labels that each got.

#3995 Update plugin-digitalocean-plugin.yml
  permissions/plugin-digitalocean-plugin.yml
Labels: initial login OK

#3997 added new user to servicenow-devops. plugin access
  permissions/plugin-servicenow-devops.yml
Labels: needs authorization

#4016 Bump pom version to 4.85
  src/main/java/io/jenkins/infra/repository_permissions_updater/hosting/MavenVerifier.java
Labels: enhancement
