Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2024-12, with the labels that each got.

#4217 added user udaykiran_aqua which refers to y-udaykiran96
  permissions/plugin-aqua-security-scanner.yml
Labels: authorization OK

#4221 Added a new uploader with jenkins account id kumar99, github ID behar…
  permissions/plugin-aqua-security-scanner.yml
Labels: initial login OK, authorization OK

#4219 plugin-accurev.yml update as required for adoption. Removal of two contributors (@poojavishal and @abmohantyj) who are not with OpenText anymore.
  permissions/plugin-accurev.yml
Labels: needs authorization, needs initial login

#4214 Add new maintainers to the plugin repo
  permissions/plugin-cloudaeye.yml
Labels: authorization OK

#4213 Add upload permissions for blackduck-coverity-on-polaris-plugin
  permissions/plugin-blackduck-coverity-on-polaris.yml
Labels: needs authorization

#4223 Permission request for metrics aggregation and pull request monitoring plugins
  permissions/plugin-metrics-aggregation.yml
  permissions/plugin-pull-request-monitoring.yml
Labels: authorization OK

#4232 Enable CD for Kerberos SSO
  permissions/plugin-kerberos-sso.yml
Labels: needs authorization
