Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2025-07, with the labels that each got.

#4312 Update plugin-anka-build.yml
  permissions/plugin-anka-build.yml
Labels: needs authorization, needs initial login

#4546 Update developers list for cloudbees-enabler-plugin
  permissions/plugin-cloudbees-enabler.yml
Labels: authorization OK

#4522 Add butter1484 to ec2-fleet-plugin
  permissions/plugin-ec2-fleet.yml
Labels: needs authorization
