Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2025-02, with the labels that each got.

#4272 Adopt ansible-tower-plugin
  permissions/plugin-ansible-tower.yml
Labels: needs authorization, initial login OK

#4291 request to get co-maintainer for JiraTestResultReporter-plugin
  permissions/plugin-JiraTestResultReporter.yml
Labels: needs initial login, authorization OK

#4290 Removes inactive maintainer from display-console-output plugin
  permissions/plugin-display-console-output.yml
Labels: needs authorization

#4311 Adopt Copy Data To Workspace Plugin
  permissions/plugin-copy-data-to-workspace-plugin.yml
Labels: needs initial login

#4212 chore: Update OpenShift team
  teams/openshift-developers.yml
Labels: authorized unless rejected, initial login OK
