Repository jenkins-infra/repository-permissions-updater, pull requests merged in 2025-03, with the labels that each got.

#3894 adding jondaley to developer list since the plugin is currently up fo…
  permissions/plugin-parameterized-trigger.yml
Labels: initial login OK, authorization OK

#4341 Adopt buildtriggerbadge-plugin
  permissions/plugin-buildtriggerbadge.yml
Labels: needs authorization, authorized unless rejected, initial login OK

#4347 Update plugin-deployit-plugin.yml
  permissions/plugin-deployit-plugin.yml
Labels: needs authorization, initial login OK

#4303 Adopt Github Release Plugin
  permissions/plugin-github-release.yml
Labels: authorized unless rejected, initial login OK

#4382 Add 'janfaracik' as a maintainer of the 'Solarized theme' plugin
  permissions/plugin-solarized-theme.yml
Labels: authorization OK
